language: c

compiler:
  - clang
  - gcc

before_install:
  - sudo add-apt-repository ppa:dns/gnu --yes
  - sudo apt-get update -qq
  - sudo apt-get install -y libmicrohttpd-dev libjansson-dev libnice-dev libssl-dev libsrtp-dev
  - sudo apt-get install -y libglib2.0-devlibogg-dev libini-config-dev libsofia-sip-ua-dev
  - sudo apt-get install -y libcollection-dev libavutil-dev libavcodec-dev libavformat-dev
  - sudo apt-get install -y libtool autoconf automake make bison flex gtk-doc-tools gcc cmake indent glib-2.0 clang
  - wget https://github.com/cisco/libsrtp/archive/v1.5.0.tar.gz
  - tar xfv v1.5.0.tar.gz
  - cd libsrtp-1.5.0
  - ./configure --prefix=/usr --enable-openssl --libdir=/usr/lib64
  - make libsrtp.so
  - sudo make uninstall
  - sudo make install
  - cd ..
  - rm -fr usrsctp
  - git clone https://github.com/sctplab/usrsctp
  - cd usrsctp
  - ./bootstrap
  - ./configure --prefix=/usr && make && make uninstall && make install
  - cd ..
  - rm -fr libwebsockets
  - git clone git://git.libwebsockets.org/libwebsockets
  - cd libwebsockets
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
  - make
  - sudo make install
  - sudo make configs
  - cd ..
  - git clone https://github.com/meetecho/janus-gateway.git
  - cd janus-gateway
  - ./autogen.sh
  - ./configure --prefix=/opt/janus --disable-docs --disable-rabbitmq --enable-post-processing
  - make
  - sudo make install
  - cd ..

script:
  - ./autogen.sh
  - ./configure --prefix=/opt/janus
  - make
  - sudo make install
